image: ubuntu:xenial
.job_compiling:
  script: &build_script
    - cd kernel
    - apt-get update -qyy
    - apt-get install -qyy curl bc make git build-essential
    - apt-get --yes install libglib2.0-dev curl flex g++-multilib gcc-multilib gnupg gperf lib32ncurses5-dev lib32z1-dev libesd0-dev libncurses5-dev libsdl1.2-dev libwxgtk-media3.0-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev
    - git clone https://bitbucket.org/matthewdalex/arm-linux-androideabi-4.9.git
    - export PATH=$PATH:$PWD/arm-linux-androideabi-4.9/bin/
    - export ARCH=arm
    - export TARGET_PRODUCT=huaqin82_wet_e_jb5
    - export ARCH_MTK_PLATFORM=mt6582
    - export SUBARCH=arm
    - export CROSS_COMPILE=$PWD/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-
    - export CROSS_COMPILE=arm-linux-androideabi
    - make defconfig
    - make zImage
job_compiling: 
  stage: build
  tags:
    - gitlab-org
  script: *build_script
