image: ubuntu:xenial
.job_compiling:
  script: &build_script
    - cd kernel
    - apt-get update -qyy
    - apt-get install -qyy curl bc make git build-essential
    - apt-get --yes install libglib2.0-dev curl flex g++-multilib gcc-multilib gnupg gperf lib32ncurses5-dev lib32z1-dev libesd0-dev libncurses5-dev libsdl1.2-dev libwxgtk-media3.0-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev
    - git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9
    - export PATH=$PATH:$PWD/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9/bin/
    - export ARCH=arm
    - export TARGET_PRODUCT=huaqin82_wet_e_jb5
    - export ARCH_MTK_PLATFORM=mt6582
    - export SUBARCH=arm
    - export CROSS_COMPILE=$PWD/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9/bin/aarch64-linux-android
    - make clean
    - make mrproper
    - make versatile_defconfig
job_compiling: 
  stage: build
  tags:
    - gitlab-org
  script: *build_script
